language: objective-c
osx_image: xcode10
rvm: 2.3.0
install:
  - bundle install
  - travis_wait 30 bundle exec pod repo update --silent
  - travis_wait 30 bundle exec pod install
before_script:
  # - ./script/disable_sparkle.sh
script:
  # TODO: remove this work around for cocoapods bug
  # https://github.com/CocoaPods/CocoaPods/issues/7708#issuecomment-423668677
  - export EXPANDED_CODE_SIGN_IDENTITY=""
  - set -o pipefail && xcodebuild -workspace Hakumai.xcworkspace -scheme Hakumai -configuration Debug -destination 'platform=OS X' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | bundle exec xcpretty -c
cache:		 
  - bundler 
  - cocoapods
